### ISSUE TITLE
Uncaught TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by karthick678** [Peteous/atom-open-bash-git#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [open-bash-git](https://github.com/Peteous/atom-open-bash-git) package 2.3.3

### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:395

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at exports.spawn (child_process.js:508:38)
    at Object.exports.execFile (child_process.js:224:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:199:20)
    at Object.exports.exec (child_process.js:154:18)
    at Object.childProcess.(anonymous function) [as exec] (ELECTRON_ASAR.js:689:22)
    at open (/packages/open-bash-git/index.coffee:33:28)
    at /packages/open-bash-git/index.coffee:52:9)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:49.8.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:49.8.0 core:select-all (input.autocomplete.autocomplete-input.autocomplete-text)
     -1:48.1.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:48 core:select-all (input.hidden-input)
     -1:46.7.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:46.6.0 core:select-all (input.hidden-input)
  4x -1:45.8.0 core:backspace (input.hidden-input)
     -1:44.8.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:44.6.0 core:paste (input.hidden-input)
     -1:43.9.0 core:confirm (input.hidden-input)
  3x -1:37.3.0 core:page-down (div.panels-item)
  5x -1:35.7.0 core:page-up (div.panels-item)
 10x -1:33.2.0 core:backspace (input.hidden-input)
     -1:29 core:confirm (input.hidden-input)
  3x -0:10.4.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -0:07.4.0 open-shell-active-directory:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-terminal 0.8.0 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
open-bash-git 2.3.3 
```

**Comment by pieczorx** [comment]
up

**Comment by stevelinus** [comment]
up

**Comment by sbrl** [comment]
I get this on Ubuntu 18.10 with the latest version of Atom too.

**Comment by mytheine** [comment]
up

**Comment by blockingthesky** [comment]
yes

**Comment by cmsimpson31** [comment]
up

**Comment by diveyez** [comment]
Still not fixed? No idea where to begin. I guess someone had to pull a leg !

**Comment by ghost** [comment]
still happening
