### ISSUE TITLE
Uncaught The "file" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by 941Zeke** [Peteous/atom-open-bash-git#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [open-bash-git](https://github.com/Peteous/atom-open-bash-git) package 2.3.3

### Stack Trace

Uncaught The "file" argument must be of type string. Received type undefined

```
At child_process.js:409

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at normalizeSpawnArguments (child_process.js:409:11)
    at spawn (child_process.js:534:38)
    at Object.execFile (child_process.js:230:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:193:20)
    at Object.exec (child_process.js:160:18)
    at Object.exec (ELECTRON_ASAR.js:746:23)
    at open (/packages/open-bash-git/index.coffee:33:28)
    at /packages/open-bash-git/index.coffee:52:9)
    at CommandRegistry.handleCommandEvent (/private/var/folders/w0/y40wl_sd02lf5cnqbg4syn_1h3rh3k/T/AppTranslocation/AD33EF38-D385-4D7D-8DF2-68743432A1B2/d/Atom.app/Contents/Resources/app/static/<embedded>:11:348736)
    at KeymapManager.dispatchCommandEvent (/private/var/folders/w0/y40wl_sd02lf5cnqbg4syn_1h3rh3k/T/AppTranslocation/AD33EF38-D385-4D7D-8DF2-68743432A1B2/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1248155)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/w0/y40wl_sd02lf5cnqbg4syn_1h3rh3k/T/AppTranslocation/AD33EF38-D385-4D7D-8DF2-68743432A1B2/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1244289)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/w0/y40wl_sd02lf5cnqbg4syn_1h3rh3k/T/AppTranslocation/AD33EF38-D385-4D7D-8DF2-68743432A1B2/d/Atom.app/Contents/Resources/app/static/<embedded>:11:283942)
```

### Commands

```
     -8:01.6.0 editor:indent (input.hidden-input)
     -8:01.1.0 core:backspace (input.hidden-input)
     -8:00.6.0 snippets:next-tab-stop (input.hidden-input)
     -8:00.6.0 snippets:expand (input.hidden-input)
     -8:00.6.0 editor:indent (input.hidden-input)
  7x -8:00.2.0 core:backspace (input.hidden-input)
  2x -7:57.3.0 editor:newline (input.hidden-input)
     -7:55.2.0 core:backspace (input.hidden-input)
     -7:41.8.0 github:toggle-git-tab (input.hidden-input)
  9x -1:50.9.0 open-shell-active-directory:open (div.tool-panel.tree-view)
  3x -0:23.1.0 core:backspace (input.hidden-input)
     -0:17.7.0 core:move-right (input.hidden-input)
  2x -0:11.5.0 core:delete (input.hidden-input)
     -0:10.1.0 core:backspace (input.hidden-input)
     -0:09.0 editor:newline (input.hidden-input)
  2x -0:07.0 open-shell-active-directory:open (input.hidden-input)
```

### Non-Core Packages

```
atom-bash 1.1.1 
bash-bang-syntax 0.3.0 
blueforest-syntax 0.5.1 
dash-syntax 0.4.2 
ide-bash 1.0.11 
open-bash-git 2.3.3 
```

**Comment by nafonso** [comment]
Any info about this being fixed? Still happening.
